# Development only.

services:
  server:
    build: .
    ports:
      - 5173:5173
    environment:
      - NODE_ENV=development
      - PORT=5173
      - SESSION_SECRET=dev
      - MONGO_URL=mongodb://dev:dev@mongo:27017
      - MONGO_DB_NAME=dev
      - RESEND_API_KEY=dev
    volumes:
      - .:/code
      - /code/node_modules
    networks:
      - bridge
    depends_on:
      - mongo

  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=dev
      - MONGO_INITDB_ROOT_PASSWORD=dev
      - MONGO_INITDB_DATABASE=dev
    volumes:
      - mongo-data:/data/db
      - ./database/init/development:/docker-entrypoint-initdb.d
    networks:
      - bridge
    healthcheck:
      test: mongosh --eval 'db.runCommand("ping").ok' --quiet
      start_period: 30s

volumes:
  mongo-data:


networks:
  bridge:
